Repository kubermatic/mla, pull requests merged in 2021-06, with the labels that each got.

#31 Upgrade Loki to 2.2.1
  charts/loki-distributed/Chart.yaml
  charts/loki-distributed/README.md
  charts/loki-distributed/README.md.gotmpl
  charts/loki-distributed/ci/persistence-values.yaml
  charts/loki-distributed/templates/NOTES.txt
  charts/loki-distributed/templates/compactor/_helpers-compactor.tpl
  charts/loki-distributed/templates/compactor/deployment-compactor.yaml
  charts/loki-distributed/templates/compactor/persistentvolumeclaim-compactor.yaml
  charts/loki-distributed/templates/compactor/service-compactor.yaml
  charts/loki-distributed/templates/compactor/serviceaccount-compactor.yaml
  charts/loki-distributed/templates/compactor/servicemonitor-compactor.yaml
  charts/loki-distributed/templates/configmap.yaml
  charts/loki-distributed/templates/distributor/deployment-distributor.yaml
  charts/loki-distributed/templates/distributor/service-distributor.yaml
  charts/loki-distributed/templates/distributor/servicemonitor-distributor.yaml
  charts/loki-distributed/templates/gateway/configmap-gateway.yaml
  charts/loki-distributed/templates/gateway/deployment-gateway.yaml
  charts/loki-distributed/templates/gateway/ingress-gateway.yaml
  charts/loki-distributed/templates/gateway/poddisruptionbudget-gateway.yaml
  charts/loki-distributed/templates/gateway/secret-gateway.yaml
  charts/loki-distributed/templates/gateway/service-gateway.yaml
  charts/loki-distributed/templates/ingester/service-ingester.yaml
  charts/loki-distributed/templates/ingester/servicemonitor-ingester.yaml
  charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
  charts/loki-distributed/templates/memcached-chunks/service-memcached-chunks.yaml
  charts/loki-distributed/templates/memcached-chunks/servicemonitor-memcached-chunks.yaml
  charts/loki-distributed/templates/memcached-frontend/service-memcached-frontend.yaml
  charts/loki-distributed/templates/memcached-frontend/servicemonitor-memcached-frontend.yaml
  charts/loki-distributed/templates/memcached-index-queries/service-memcached-index-queries.yaml
  charts/loki-distributed/templates/memcached-index-queries/servicemonitor-memcached-index-queries.yaml
  charts/loki-distributed/templates/memcached-index-writes/service-memcached-index-writes.yaml
  charts/loki-distributed/templates/memcached-index-writes/servicemonitor-memcached-index-writes.yaml
  charts/loki-distributed/templates/networkpolicy.yaml
  charts/loki-distributed/templates/querier/service-querier.yaml
  charts/loki-distributed/templates/querier/servicemonitor-querier.yaml
  charts/loki-distributed/templates/querier/statefulset-querier.yaml
  charts/loki-distributed/templates/query-frontend/deployment-query-frontend.yaml
  charts/loki-distributed/templates/query-frontend/service-query-frontend.yaml
  charts/loki-distributed/templates/query-frontend/servicemonitor-query-frontend.yaml
  charts/loki-distributed/templates/ruler/deployment-ruler.yaml
  charts/loki-distributed/templates/ruler/persistentvolumeclaim-ruler.yaml
  charts/loki-distributed/templates/ruler/service-ruler.yaml
  charts/loki-distributed/templates/ruler/servicemonitor-ruler.yaml
  charts/loki-distributed/templates/table-manager/deployment-table-manager.yaml
  charts/loki-distributed/templates/table-manager/poddisruptionbudget-table-manager.yaml
  charts/loki-distributed/templates/table-manager/service-table-manager.yaml
  charts/loki-distributed/templates/table-manager/servicemonitor-table-manager.yaml
  charts/loki-distributed/values.yaml
  config/loki/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#34 Add Prow job to deploy MLA in dev
  .prow.yaml
  hack/ci/deploy-dev.sh
  hack/lib.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#35 Use Recreate deployment strategy for minio
  config/minio/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#36 Add missing dependency for memcached
  .gitignore
  charts/cortex/.gitignore
  charts/cortex/subcharts/memcached/charts/common/.helmignore
  charts/cortex/subcharts/memcached/charts/common/Chart.yaml
  charts/cortex/subcharts/memcached/charts/common/README.md
  charts/cortex/subcharts/memcached/charts/common/templates/_affinities.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/_capabilities.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/_errors.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/_images.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/_ingress.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/_labels.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/_names.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/_secrets.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/_storage.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/_tplvalues.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/_utils.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/_warnings.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/validations/_cassandra.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/validations/_mariadb.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/validations/_mongodb.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/validations/_postgresql.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/validations/_redis.tpl
  charts/cortex/subcharts/memcached/charts/common/templates/validations/_validations.tpl
  charts/cortex/subcharts/memcached/charts/common/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#33 Upgrade grafana to 8.0.1
  charts/grafana/Chart.yaml
  charts/grafana/README.md
  charts/grafana/templates/_helpers.tpl
  charts/grafana/templates/_pod.tpl
  charts/grafana/templates/configmap.yaml
  charts/grafana/templates/deployment.yaml
  charts/grafana/templates/hpa.yaml
  charts/grafana/templates/image-renderer-service.yaml
  charts/grafana/templates/ingress.yaml
  charts/grafana/templates/podsecuritypolicy.yaml
  charts/grafana/templates/secret.yaml
  charts/grafana/templates/service.yaml
  charts/grafana/templates/statefulset.yaml
  charts/grafana/values.yaml
  config/grafana/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#30 add default grafana dashboards
  config/grafana/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#38 Use existing secret for minio
  config/minio/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#39 Increase timeout to deploy cortex
  hack/ci/deploy-dev.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#40 Use existing secret for grafana
  config/grafana/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#41 Add MLA secrets helm chart
  charts/mla-secrets/Chart.yaml
  charts/mla-secrets/templates/grafana-secret.yaml
  charts/mla-secrets/templates/minio-secret.yaml
  charts/mla-secrets/values.yaml
  config/mla-secrets/values.yaml
  hack/deploy-seed.sh
Labels: approved, dco-signoff: yes, lgtm, size/L
