Repository kubermatic/mla, pull requests merged in 2021-08, with the labels that each got.

#49 Update README.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#50 Use larger volume for Cortex ingesters
  config/cortex/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#51 Scale up components on Loki write path
  config/cortex/values.yaml
  config/loki/values.yaml
  hack/deploy-seed.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#52 Fix incorrect storegw volume size
  config/cortex/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#53 Remove the mla secret generation out of deploy-seed.sh
  hack/deploy-seed.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#55 Decrease storage data retention period
  config/cortex/values.yaml
  config/loki/values.yaml
  config/minio-lifecycle-mgr/values.yaml
Labels: approved, lgtm, dco-signoff: yes, size/M

#56 Add common Grafana dashboards
  config/grafana/values.yaml
  dashboards/kkp-kubernetes.yaml
  dashboards/kubernetes-overview.yaml
  hack/ci/deploy-dev.sh
  hack/deploy-seed.sh
  hack/generate-kkp-dashboards.sh
Labels: approved, lgtm, dco-signoff: yes, size/XXL
