Repository kubermatic/mla, pull requests merged in 2021-11, with the labels that each got.

#66 Use helm3 in the ci script
  hack/ci/deploy-dev.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#67 Upgrade grafana to 8.2.3
  charts/grafana/Chart.yaml
  charts/grafana/README.md
  charts/grafana/templates/_helpers.tpl
  charts/grafana/templates/_pod.tpl
  charts/grafana/templates/dashboards-json-configmap.yaml
  charts/grafana/templates/image-renderer-deployment.yaml
  charts/grafana/templates/ingress.yaml
  charts/grafana/templates/podsecuritypolicy.yaml
  charts/grafana/templates/role.yaml
  charts/grafana/templates/rolebinding.yaml
  charts/grafana/templates/tests/test-podsecuritypolicy.yaml
  charts/grafana/values.yaml
Labels: approved, lgtm, dco-signoff: yes, size/L

#70 fix mla consul
  config/consul/values.yaml
Labels: approved, lgtm, dco-signoff: yes, size/S

#71 Allow using existing minio in MLA setup
  charts/mla-secrets/Chart.yaml
  charts/mla-secrets/templates/grafana-secret.yaml
  charts/mla-secrets/templates/minio-secret.yaml
  charts/mla-secrets/values.yaml
  config/mla-secrets/values.yaml
  hack/deploy-seed.sh
Labels: approved, lgtm, dco-signoff: yes, size/M

#74 add prometheus-scraping annotations for loki
  config/loki/values.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#75 Remove jiachengxu from OWNERS
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, dco-signoff: yes
