Repository kubermatic/mla, pull requests merged in 2021-09, with the labels that each got.

#58 add support of cortex runtime config
  config/cortex/runtime-config.yaml
  config/cortex/values.yaml
  hack/ci/deploy-dev.sh
  hack/deploy-seed.sh
Labels: approved, lgtm, dco-signoff: yes, size/M

#59 Update IAP example config according to the latest changes
  config/iap/values.example.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#60 remove id from dashboard
  dashboards/kubernetes-overview.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#61 README updates + add related files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  DCO
  LICENSE
  NOTICE
  README.md
  Zenhub.md
Labels: approved, lgtm, dco-signoff: yes, size/XL
