Repository kubermatic/mla, pull requests merged in 2022-04, with the labels that each got.

#86 Synchronize OWNERS_ALIASES file with Github teams
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, dco-signoff: yes

#92 Download dependencies during the deployment of mla
  hack/ci/deploy-dev.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#93 Fetch chart dependencies in CI runs
  hack/ci/deploy-dev.sh
  hack/deploy-seed.sh
  hack/fetch-chart-dependencies.sh
Labels: approved, lgtm, dco-signoff: yes, size/M

#94 Fix reference to lib.sh in fetch-chart-dependencies.sh
  hack/fetch-chart-dependencies.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#95 Fix directory used to run fetch-chart-dependencies script
  hack/fetch-chart-dependencies.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#96 Switch to new build image in CI, use helm3 as deafult
  .prow.yaml
  hack/ci/deploy-dev.sh
Labels: approved, lgtm, dco-signoff: yes, size/S

#97 Remove manual installation of cortex runtime-config ConfigMap
  config/cortex/runtime-config.yaml
  hack/ci/deploy-dev.sh
  hack/deploy-seed.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#98 Fix values specified in config directory for charts
  config/consul/values.yaml
  config/cortex/values.yaml
  config/grafana/values.yaml
  config/loki/values.yaml
  config/minio/values.yaml
Labels: approved, lgtm, dco-signoff: yes, size/XXL

#99 Set runtimeconfigmap.create=true in Cortex values
  config/cortex/values.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#100 Fix minio secret references in cortex
  charts/minio-lifecycle-mgr/templates/lifecycle-mgr-configmap.yaml
  config/cortex/values.yaml
Labels: approved, lgtm, dco-signoff: yes, size/S

#101 Fix cortex-runtime-cfg file name
  config/cortex/values.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#102 Fix reference for secret in cortex chart
  config/cortex/values.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#103 Add memcached as top-level dependency in cortex & tests based on default configs
  charts/consul/test/config.yaml
  charts/consul/test/config.yaml.out
  charts/cortex/Chart.lock
  charts/cortex/Chart.yaml
  charts/cortex/test/config.yaml
  charts/cortex/test/config.yaml.out
  charts/cortex/test/default.yaml.out
  charts/grafana/test/config.yaml
  charts/grafana/test/config.yaml.out
  charts/loki-distributed/test/config.yaml
  charts/loki-distributed/test/config.yaml.out
  charts/minio/test/config.yaml
  charts/minio/test/config.yaml.out
Labels: approved, lgtm, dco-signoff: yes, size/XXL

#104 Do no run additional helm dep update in deploy-seed.sh
  hack/deploy-seed.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#105 Do not run helm dep update in deploy-dev.sh script
  hack/ci/deploy-dev.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#106 Update cortex Chart.lock
  charts/cortex/Chart.lock
Labels: size/XS, approved, lgtm, dco-signoff: yes

#107 Limit CI job on 4Gi memory
  .prow.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#108 Use minio's rootUser and rootPassword in loki
  charts/loki-distributed/test/config.yaml.out
  config/loki/values.yaml
Labels: approved, lgtm, dco-signoff: yes, size/M

#109 Revert cortex runtime config changes
  config/cortex/runtime-config.yaml
  config/cortex/values.yaml
  hack/ci/deploy-dev.sh
  hack/deploy-seed.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#110 Add workaroud for Cortex Alertmanager service discovery bug
  charts/cortex/templates/cortex-alertmanager-headless-kkp.yaml
  charts/cortex/test/config.yaml.out
  charts/cortex/test/default.yaml.out
  config/cortex/values.yaml
  config/loki/values.yaml
Labels: approved, lgtm, dco-signoff: yes, size/XL

#111 Add information about 0.1.1 version compatibility
  README.md
Labels: size/XS, approved, lgtm, dco-signoff: yes

#91 alertmanager-proxy: fix compatibility with KKP 2.20
  charts/alertmanager-proxy/templates/authzserver-clusterrole.yaml
  charts/alertmanager-proxy/values.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
