Repository kubermatic/mla, pull requests merged in 2023-01, with the labels that each got.

#148 Include static version of memcached charts for cortex
  charts/cortex/Chart.lock
  charts/cortex/Chart.yaml
  charts/cortex/charts/memcached/.helmignore
  charts/cortex/charts/memcached/Chart.lock
  charts/cortex/charts/memcached/Chart.yaml
  charts/cortex/charts/memcached/README.md
  charts/cortex/charts/memcached/charts/common/.helmignore
  charts/cortex/charts/memcached/charts/common/Chart.yaml
  charts/cortex/charts/memcached/charts/common/README.md
  charts/cortex/charts/memcached/charts/common/templates/_affinities.tpl
  charts/cortex/charts/memcached/charts/common/templates/_capabilities.tpl
  charts/cortex/charts/memcached/charts/common/templates/_errors.tpl
  charts/cortex/charts/memcached/charts/common/templates/_images.tpl
  charts/cortex/charts/memcached/charts/common/templates/_ingress.tpl
  charts/cortex/charts/memcached/charts/common/templates/_labels.tpl
  charts/cortex/charts/memcached/charts/common/templates/_names.tpl
  charts/cortex/charts/memcached/charts/common/templates/_secrets.tpl
  charts/cortex/charts/memcached/charts/common/templates/_storage.tpl
  charts/cortex/charts/memcached/charts/common/templates/_tplvalues.tpl
  charts/cortex/charts/memcached/charts/common/templates/_utils.tpl
  charts/cortex/charts/memcached/charts/common/templates/_warnings.tpl
  charts/cortex/charts/memcached/charts/common/templates/validations/_cassandra.tpl
  charts/cortex/charts/memcached/charts/common/templates/validations/_mariadb.tpl
  charts/cortex/charts/memcached/charts/common/templates/validations/_mongodb.tpl
  charts/cortex/charts/memcached/charts/common/templates/validations/_postgresql.tpl
  charts/cortex/charts/memcached/charts/common/templates/validations/_redis.tpl
  charts/cortex/charts/memcached/charts/common/templates/validations/_validations.tpl
  charts/cortex/charts/memcached/charts/common/values.yaml
  charts/cortex/charts/memcached/ci/values-production.yaml
  charts/cortex/charts/memcached/templates/NOTES.txt
  charts/cortex/charts/memcached/templates/_helpers.tpl
  charts/cortex/charts/memcached/templates/deployment.yaml
  charts/cortex/charts/memcached/templates/extra-list.yaml
  charts/cortex/charts/memcached/templates/hpa.yaml
  charts/cortex/charts/memcached/templates/pdb.yaml
  charts/cortex/charts/memcached/templates/secrets.yaml
  charts/cortex/charts/memcached/templates/service.yaml
  charts/cortex/charts/memcached/templates/serviceaccount.yaml
  charts/cortex/charts/memcached/templates/servicemonitor.yaml
  charts/cortex/charts/memcached/templates/statefulset.yaml
  charts/cortex/charts/memcached/templates/svc-metrics.yaml
  charts/cortex/charts/memcached/values.yaml
  hack/fetch-chart-dependencies.sh
Labels: kind/bug, approved, lgtm, dco-signoff: yes, size/XXL

#149 Update compatibility matrix to include KKP 2.21
  README.md
Labels: kind/documentation, size/XS, approved, lgtm, dco-signoff: yes

#151 Include static version of memcached charts for cortex (#148)
  charts/cortex/Chart.lock
  charts/cortex/Chart.yaml
  charts/cortex/charts/memcached/.helmignore
  charts/cortex/charts/memcached/Chart.lock
  charts/cortex/charts/memcached/Chart.yaml
  charts/cortex/charts/memcached/README.md
  charts/cortex/charts/memcached/charts/common/.helmignore
  charts/cortex/charts/memcached/charts/common/Chart.yaml
  charts/cortex/charts/memcached/charts/common/README.md
  charts/cortex/charts/memcached/charts/common/templates/_affinities.tpl
  charts/cortex/charts/memcached/charts/common/templates/_capabilities.tpl
  charts/cortex/charts/memcached/charts/common/templates/_errors.tpl
  charts/cortex/charts/memcached/charts/common/templates/_images.tpl
  charts/cortex/charts/memcached/charts/common/templates/_ingress.tpl
  charts/cortex/charts/memcached/charts/common/templates/_labels.tpl
  charts/cortex/charts/memcached/charts/common/templates/_names.tpl
  charts/cortex/charts/memcached/charts/common/templates/_secrets.tpl
  charts/cortex/charts/memcached/charts/common/templates/_storage.tpl
  charts/cortex/charts/memcached/charts/common/templates/_tplvalues.tpl
  charts/cortex/charts/memcached/charts/common/templates/_utils.tpl
  charts/cortex/charts/memcached/charts/common/templates/_warnings.tpl
  charts/cortex/charts/memcached/charts/common/templates/validations/_cassandra.tpl
  charts/cortex/charts/memcached/charts/common/templates/validations/_mariadb.tpl
  charts/cortex/charts/memcached/charts/common/templates/validations/_mongodb.tpl
  charts/cortex/charts/memcached/charts/common/templates/validations/_postgresql.tpl
  charts/cortex/charts/memcached/charts/common/templates/validations/_redis.tpl
  charts/cortex/charts/memcached/charts/common/templates/validations/_validations.tpl
  charts/cortex/charts/memcached/charts/common/values.yaml
  charts/cortex/charts/memcached/ci/values-production.yaml
  charts/cortex/charts/memcached/templates/NOTES.txt
  charts/cortex/charts/memcached/templates/_helpers.tpl
  charts/cortex/charts/memcached/templates/deployment.yaml
  charts/cortex/charts/memcached/templates/extra-list.yaml
  charts/cortex/charts/memcached/templates/hpa.yaml
  charts/cortex/charts/memcached/templates/pdb.yaml
  charts/cortex/charts/memcached/templates/secrets.yaml
  charts/cortex/charts/memcached/templates/service.yaml
  charts/cortex/charts/memcached/templates/serviceaccount.yaml
  charts/cortex/charts/memcached/templates/servicemonitor.yaml
  charts/cortex/charts/memcached/templates/statefulset.yaml
  charts/cortex/charts/memcached/templates/svc-metrics.yaml
  charts/cortex/charts/memcached/values.yaml
  charts/cortex/test/config.yaml.out
  charts/cortex/test/default.yaml.out
  hack/fetch-chart-dependencies.sh
Labels: approved, lgtm, dco-signoff: yes, size/XXL

#152 Fix fetch-chart-dependencies.sh
  hack/fetch-chart-dependencies.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#153 Fix file mode for `hack/fetch-chart-dependencies.sh`
  hack/fetch-chart-dependencies.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes, kind/cleanup
